import 'package:shared_preferences/shared_preferences.dart';

import 'device_credentials.dart';

/// Where the device's long-lived credential is kept between launches.
///
/// The credential is provisioned by an operator, not generated by the client,
/// so it has to survive restarts. Abstracted so a platform keystore can
/// replace the default without touching the bootstrap.
abstract interface class CredentialStore {
  /// Returns null when nothing usable is stored.
  Future<DeviceCredentials?> load();

  Future<void> save(DeviceCredentials credentials);

  Future<void> clear();
}

/// [CredentialStore] backed by `shared_preferences`.
///
/// Plain storage, not a keystore: v1 has no TLS and no auth beyond the device
/// token, and the token is already readable in the app's own data directory.
/// Moving to `flutter_secure_storage` later means implementing this interface
/// and nothing else.
class SharedPrefsCredentialStore implements CredentialStore {
  SharedPrefsCredentialStore({SharedPreferences? preferences})
    : _preferences = preferences;

  static const String deviceIdKey = 'device_id';
  static const String deviceTokenKey = 'device_token';

  SharedPreferences? _preferences;

  Future<SharedPreferences> get _prefs async =>
      _preferences ??= await SharedPreferences.getInstance();

  @override
  Future<DeviceCredentials?> load() async {
    final prefs = await _prefs;
    final id = prefs.getString(deviceIdKey);
    final token = prefs.getString(deviceTokenKey);

    if (id == null || id.isEmpty || token == null || token.isEmpty) {
      return null;
    }

    final credentials = DeviceCredentials(deviceId: id, deviceToken: token);

    // A value left behind by an earlier build (the old client stored a UUIDv4
    // here) would otherwise produce a stream of unexplained 401s. Treat it as
    // "nothing stored" so the operator is asked for a real credential.
    if (!credentials.hasValidDeviceId) return null;

    return credentials;
  }

  @override
  Future<void> save(DeviceCredentials credentials) async {
    final prefs = await _prefs;
    await prefs.setString(deviceIdKey, credentials.deviceId);
    await prefs.setString(deviceTokenKey, credentials.deviceToken);
  }

  @override
  Future<void> clear() async {
    final prefs = await _prefs;
    await prefs.remove(deviceIdKey);
    await prefs.remove(deviceTokenKey);
  }
}
